### PR TITLE
6809opt

### PR DESCRIPTION
**Pull request by Samuel-DEVULDER**
I kind of promised a PR for this week-end, and here we are.

This branch doesn't contain all I wanted to do, but yet it provides a reasonably well featured optimizer. For information with it, the starfield runs over 30 fps with 21 stars :)
dcmoto08

I had cleaned up the code, implemented a lightweight [data-flow analysis tool](https://github.com/Samuel-DEVULDER/ugbasic/issues/2), and added a bunch of comments to describe the operations performed.

It is now a bit more than a simple "peephole" optimizer, and hopefully the comments I provide might help discuss & porting the ideas to other platforms.

You can now review the code and indicate what you'd like to be changed/cleaned, like memory allocation of buffer overrun  that I totally ignored or support for disabling all or unsafe optimizations, or to remove the comments in the output asm (these helpful to me but not necessarily for the end-user).

Note: I only tested it on the starfield. I'll try to test other sources next week, so this branch might still evolve. I don't know how a PR is supposed to work when the branch evolves. We'll see.

### CODE REVIEW

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER, **thank you for your contribution!**

I started to merge your version with the `main` branch, to carry on when you have finished the tests of the various examples. If you get to a stable point I would say to open a different PR, in order to be able to release the peephole optimized for PC128OP/MO5 on the next stable release (1.7?).

In the meanwhile, I found one conflict on `startup.asm` of `pc128op`, that seems older than the one that we released on #278, moreover it refers to `MO5STARTUP3`. It is ok?

Thank you again!

**Comment by Samuel-DEVULDER** [comment]
MO5STARTUP3 stuff is to clear the direct page. I added these because now the optimizer is able to move some variables (initialized with 0) to direct page, reducing the memory footprint and speeding up the code.

I'll fix the conflicts on my branch.

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER !
Could I go on with the merge on main branch?

**Comment by Samuel-DEVULDER** [comment]
At the moment I im off any development computer so there is no more pending work on that branch. In addition the various test cases seem to work the same as the original branch, so yes you can ;) go merge !I hope you could see the speed boost the optimizer gives. Typically the starfield runs over 30fps.Le 10 déc. 2021 13:30, Marco Spedaletti ***@***.***> a écrit :
Hi @Samuel-DEVULDER !
Could I go on with the merge on main branch?

**Comment by Samuel-DEVULDER** [comment]
I'm back. And I tested the new version, but all I get is compilation errors. See this comment: https://github.com/spotlessmind1975/ugbasic/commit/483a492fc49b4e19447559ce5f483072006d5049#r62063894

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER , I reverted the merge.
Take your time to make this branch stable.
I will reapply it by cherry-picking instead of merging.

**Comment by Samuel-DEVULDER** [comment]
Ok. When you speak about "this branch", do you mean 6809opt in my repo ?

I can merge it with your main, and see/correct what is going wrong (not a lot I presume).

**Comment by Samuel-DEVULDER** [comment]
Hmm.. I have just tested examples/arrays_example_01.bas on the pc128op from the "main" branch, but all I get is a blank screen. 

What did I do wrong ?

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER, thanks for the feedback!

I probably expressed myself too succinctly. What I meant is that I did merge your branch, but it obviously failed, introducing a series of errors induced by the fact that git decided, on its own, how to merge the code. It would have been best to "cherry-pick" every modification, but I trusted to the system. 

So now I've brought everything back to before the merge. Unfortunately github doesn't realize that this is a "revert", because I did a refix to avoid messing up the code even more.

So you should start from the commit you started from to detach this branch, apply your changes, merge with my actual "main" branch and finally generate a new branch to submit to pull request. Before submitting the pull request you should check that everything works.

Thanks again!

**Comment by Samuel-DEVULDER** [comment]
Okay.. but the thing is that even from your current main, the generated binary for arrays_example_01.bas displays nothing :-/

Do you have the same ? Is you main branch broken ?

**Pull request merged**
