### PR TITLE
Opt6809 revisited

### PR DESCRIPTION
**Pull request by Samuel-DEVULDER**
Merry Christmas to you!

Santa brought me a new branch which should repair pull-request #271. 

* This new version of the 6809 optimization makes better use of the B register which provide some nice and optimizations.
* Memory footprint is reduced and the generated code is slightly faster when using plot since the parameters are now passed in registers (we have enough of them for this call). I wish I had the time to do the same for TEXTAT (and may be hand optimize the ASM). May be this will come next year ;)
* The various optimizations passes are now more cleanly separated from one another
* Several optimisations phases (peephole / unread variable elimination / variable relocation in direct-page / variable inlining) can be disabled using #defines (this helps identifying bugs)
* I did successfully test the examples. They seem to work the same as on the origin main branch.
* the Star Field is even faster with this branch:
image

### CODE REVIEW

**Comment by spotlessmind1975** [comment]
Optimization merged.

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER **, thank you so much for the beautiful christmas gift!** 

I merged it in the `main` branch, and I published version `1.7.2`, so that everyone can benefit from it, even those who use the IDE. I think I'll use the starry sky demo in the main site gallery, too.

**Thanks again and happy holidays!**

**Comment by Samuel-DEVULDER** [comment]
Many thanks :D 

I hope it'll run correctly on all machines. It gave me lots of inspiration for optimizations. Lots are included but one required to slightly change the infrastructure to ease the optimizer which I considered to be a bad approach hasn't been added. 

There a room for improvements in the star field:
* A possible evolution is to change the screen mode on key-press.
* I wish Santa had had time to add a little MOB sleigh (or is it bobsleigh ?) passing by once in a while, but he really seemed to be too busy in that time ;)

**Comment by spotlessmind1975** [comment]
Hi @Samuel-DEVULDER, I disturb you just to tell you that the star field demo has been added on the ugBASIC homepage, as a example of the optimizer for Motorola 6809. **Have a nice day!**

**Comment by Samuel-DEVULDER** [comment]
Great!Le 6 janv. 2022 13:03, Marco Spedaletti ***@***.***> a écrit :
Hi @Samuel-DEVULDER, I disturb you just to tell you that the star field demo has been added on the ugBASIC homepage, as a example of the optimizer for Motorola 6809. Have a nice day!

**Pull request merged**
