### PR TITLE
K7 rework

### PR DESCRIPTION
**Pull request by Samuel-DEVULDER**
My attempt to generate byte-order and length independent K7 generation

### CODE REVIEW

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER  **I would say it's a great job!**

So, I tried to merge directly, but since I worked on one of the ".asm" files it gives me a conflict. I replaced the modified file with yours, and then I aligned it with the changes. The real problem, though, is that if I merge directly I get a number of errors and problems during compilation. 

So I "cherry-picked" singular commits, with those results:
  - `5821d25 - (3 hours ago) dos2unix asm files` - ok (just fixed conflict on `mob.asm`)
  - `4de9dc5 - (2 hours ago) reworked K7-file generation` - ok
  - `a7ff313 - (2 hours ago) modifies Makefile to allow "make -jN"` - various compilation errors

In my opinion the first two commits should be put in the main branch (I will do it as soon as possible), while for the third I just have to figure out how to correct this single compilation error:

	src/ugbc.lex:4:10: fatal error: ugbc.tab.h: No such file or directory
	    4 | #include "ugbc.tab.h" /* The tokens */
	      |          ^~~~~~~~~~~~

It seems like if the code generated by the lexer is missing. 
However, seeing the makefile changes, I don't think they involve this file. 

If you have any advice, you are welcome!

**Comment by Samuel-DEVULDER** [comment]
> In my opinion the first two commits should be put in the main branch (I will do it as soon as possible), while for the third I just have to figure out how to correct this single compilation error:
> 
> ```
> src/ugbc.lex:4:10: fatal error: ugbc.tab.h: No such file or directory
>     4 | #include "ugbc.tab.h" /* The tokens */
>       |          ^~~~~~~~~~~~
> ```
> 
> It seems like if the code generated by the lexer is missing. However, seeing the makefile changes, I don't think they involve this file.
> 
> If you have any advice, you are welcome!

Hmm I was sure I did something wrong. I think this commit fixes it: https://github.com/Samuel-DEVULDER/ugbasic/commit/b64f6f63ed56692d62e0894a50900e5f0a443c84

**Comment by spotlessmind1975** [comment]
@Samuel-DEVULDER **thanks so much for the fix!**

If you push it on the **k7-work** branch of your repository, I can retrieve it and try it on the main test branch too.

Just let me know.

**Comment by Samuel-DEVULDER** [comment]
> If you push it on the **k7-work** branch of your repository, I can retrieve it and try it on the main test branch too.
> 
> Just let me know.

This should be ok by https://github.com/Samuel-DEVULDER/ugbasic/commit/b64f6f63ed56692d62e0894a50900e5f0a443c84 (hopefully)

**Comment by spotlessmind1975** [comment]
**@Samuel-DEVULDER yes, thank you, everything is perfect!**

I added your changes, so now they are part of the main branch source, especially all the changes to the ASM sources. On the occasion, then, I also reconfigured my editor, so I will not introduce more files with "CRLF".

Regarding the generation of the k7 file, for backwards compatibility I have left the old procedure for the generation of the k7 available with a special option (`-O k7o`). By default yours (`-O k7`) will be used.

Finally, I have added your changes to the main branch, so that they are also available for your fork.

**Pull request closed without merging**
